import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import {SideBar} from "@/conponents/sideBar/side-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name={'viewport'} content={'width=device-width, initial-scale=1.0'}/>
        <title>side bar</title>
      </head>
      <body className={inter.className}>
        <div className="container-fluid">
          <div className="row flex-nowrap">
            <SideBar/>
            {children}
          </div>
        </div>
      </body>
    </html>
);
}
